name: tradeos
description: "Premium High-Fidelity Trading Journal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  google_fonts: ^6.2.1
  fl_chart: ^0.66.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  # Pastikan jika ada aset (gambar/logo), didaftarkan di sini nanti
